# Generated by Django 3.2.8 on 2021-11-04 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('email',), 'permissions': (('manage_users', 'Manage customers.'), ('manage_staff', 'Manage staff.'), ('impersonate_user', 'Impersonate user.'))},
        ),
        migrations.RemoveField(
            model_name='user',
            name='date_joined',
        ),
    ]
